### ISSUE TITLE
Error with Permissions Policy header

### ISSUE THREAD

**Issue by BenjaminRouger** [DanWin/le-chat-php#102]
Hi, I've got this error on console : Error with Permissions-Policy header: Parse of permissions policy failed because of errors reported by structured header parser. 
I've tried different methods to resolve the problem of style-src unsafe inline, but nothing working
does that mean I have to move all the css?

**Comment by DanWin** [comment]
Thanks, it seems the permission policy draft has since moved to a new syntax specification and needs an update. It's an experimental feature and could still receive specification updates, which will break existing code if not updated.
See related thread on stackoverflow https://stackoverflow.com/questions/66350784/apache-error-with-permissions-policy-header-parse-of-permission-policy-failed
I'll fix this issue later today.

**Comment by BenjaminRouger** [comment]
I continue to look for my side, I await your return if you fix the problem.
