### ISSUE TITLE
Is this normal or is it bugged? Enable file uploads - No dropdown to Enable / Disable

### ISSUE THREAD

**Issue by Deepnerd** [DanWin/le-chat-php#113]
Just asking to make sure is this a bug or what. it has no disable or enable dropdown.  Thank you for your time to resolve my problem. have a great day daniel!
![SS](https://user-images.githubusercontent.com/65068062/130059495-1b987de9-a495-418b-a9dc-d9acda4c8299.PNG)

**Comment by DanWin** [comment]
That is currently how it is implemented, yes. But good point, this should be changed into a dropdown. Previously it was a dropdown enable/disable, but now it would have to be changed into a dropdown for different membership status values, because if you set it to e.g. 3, it will only let members upload a file, but not guests.

**Comment by Deepnerd** [comment]
Oh great! Thank you very much for your explanation and to your time. Always thank you so much for your great work! i would really like to be a sponsor to you but unfortunately I'm under lockdown and lost my job so I'm looking forward to support you soon when life becomes normal.  Everyone should support you and to your friends who spends a lot time on these open source projects. keep up the great work. Thank you.
