### ISSUE TITLE
it is impossible to read and understand captcha

### ISSUE THREAD

**Issue by zeus6999** [DanWin/le-chat-php#128]
Hello
it is impossible to read and understand captcha, and weigh of captcha
it seems you don't want anyone watching the demo.
do not understand you

**Comment by DanWin** [comment]
Hello @zeus6999 ,
not sure what exactly your issue is. There are 3 different difficulty settings for the captcha. A simple one, which is enough to keep out most bots and very easy to read, a harder one, which makes it more difficult to read the letters by adding noise and an extreme difficulty captcha, where you have to follow a line and type the characters as they appear. This is mostly useful to defend against more sophisticated bots, that can do OCR. As the name already suggests, it is extremely difficult to solve and should only be used in attack scenarios. You can change the captcha difficulty when going to the setup panel as a super admin.
I'm closing this issue, since I think you've accidentally enabled a more difficult captcha. If this is a real issue, please suggest what should be improved.
