### ISSUE TITLE
is it possible loading videos like pictures?

### ISSUE THREAD

**Issue by onion888** [DanWin/le-chat-php#129]
Like    [media]http://xxxxxxxxxxxxxxxxxx.mp4/webm
----------------
Any one know how to achieve this goal ?

Much appreciate~

**Comment by rexzooly** [comment]
Well yes as long as the tags used are supported, it's just another media type, just need the right means to check it

**Comment by DanWin** [comment]
You could add a filter like this: 
Match: `\[media\]([^\s]+)` Replace: `<video src="$1" autoplay>`, tick the regex box. Then you can embed a video just like the images.
Note: those videos should be very short, otherwise they will only play a few seconds until the next refresh of messages. Each time the messages are reloaded, the video will begin from the beginning.
