### ISSUE TITLE
le chat on hostingsystem

### ISSUE THREAD

**Issue by 01123581321345589144233** [DanWin/le-chat-php#56]
Hi, i cannot install le chat on Daniels hosting, so the setup action cannot find the mysql table.
All logins and users are correct,

**Comment by Artifact0** [comment]
it is easy to install on Daniel's hosting. download the master zip from here, upload that and extract it with the online file manager, rename folder, edit bottom of chat.php, and you are just about good to go. 
when you say logins and users are correct do you mean mysql user/pass?
can you provide more details to better solve the problem?
once I found the option to install it with database driver 2 and use sqli it was easier for me. that db method uses local files instead of separate server, port and login credentials. for large sites that may cause performance issues but for a small site it makes it easier to deploy and manage, much more simple. maybe this line will help you also:
``
	define('DBDRIVER', 2); // Selects the database driver to use - 0=MySQL, 1=PostgreSQL, 2=sqlite
``

**Comment by linhux** [comment]
i have setup the system with sqlite and it works, i try tomorrow to setup a new with mysql, sems to the login and databasenames are not working, so i try again and leave a report here.

**Comment by DanWin** [comment]
@linhux , if you need assistance with the setup, you can contact me by mail with your account details and I can have a look at what your issue is. There are many users using the chat script on my hosting without any issues, so I suspect there is some configuration option you overlooked when saving the DB config within the chat.php script.
