### ISSUE TITLE
Extension Installation

### ISSUE THREAD

**Issue by PyMaster22** [DanWin/le-chat-php#69]
I want to use this on my TOR site but I don't know how to install PHP extensions on my Linux PC.
Any help on installing the extensions would be amazing.

**Comment by chris-clearence** [comment]
For PHP run as root (or prefix with `sudo`
`# apt-get update && apt-get upgrade`
`# apt-get install software-properties-common`
`# add-apt-repository ppa:ondrej/php`
`# apt-get update`
`# apt install php7.4`
`# apt-get install php-pear php7.4-curl php7.4-dev php7.4-gd php7.4-mbstring php7.4-zip php7.4-mysql php7.4-xml`

Then to install extensions see [this page](https://www.php.net/manual/en/extensions.alphabetical.php) and navigate accordingly :)

**Comment by PyMaster22** [comment]
For some reason it didn't let me add the PPA but I was able to download everything still by changing 7.4 to 7.3.

**Comment by DanWin** [comment]
What does your hosting environment look like? Do you use a graphical tool like XAMPP or MAMP or did you install the webserver and PHP from your distributions repository? You can have multiple PHP versions running at the same time. When you install extensions, make sure they are for the version you are running. If you are unsure which version you are using, create a .php file in your webroot with the content `<?php phpinfo();` and then load the file in your browser. You should see a lot of details about which version you are running and which modules are currently installed.

**Comment by PyMaster22** [comment]
I'm completely confused.
I heard on the chat that the original perl version worked. Do you have any existing downloads for it?

**Comment by cypherbits** [comment]
Hi @PyMaster22 , are you installing on local or a server? Using Debian/Ubuntu or RedHat/CentOS Linux?
What version?

Old perl version is very old (as the name says) and then insecure.

**Comment by PyMaster22** [comment]
Yes I am installing the local server on Debian 10.
I don't have the Perl version (or Perl itself as of right now) of the script as of writing but do (obviously) have the PHP script.
As always any information on how to compile and run scripts is appreciated. (assume I have nothing installed that's usually how it goes)

**Comment by cypherbits** [comment]
@PyMaster22 what is your experience with PHP and web servers?

You have a Debian, so add-apt-repository ppa:ondrej/php will not work good because this ppa is meant for Ubuntu.

If you already installed PHP, well, you need a web server, like Apache, and then configure Apache to run PHP code.
Most distributions will install Apache+PHP and configure it to run PHP out of the box.

You don't have to compile PHP or run from command line to start the server. (I mean you do not run "php ChatScript.php" to start a server. You just configure a site on Apache and a web root directory and then put your PHP code there.

Do you know all that?

**Comment by PyMaster22** [comment]
I can't add ppas to my computer.
It's never worked.

**Comment by PyMaster22** [comment]
Ummmm...
PPAs?
