### ISSUE TITLE
Clean Out Chat Data

### ISSUE THREAD

**Issue by F1nx** [DanWin/le-chat-php#84]
Although this suggestion may not work because of the constant page-refreshing and lack of JavaScript, I believe this could save a lot of space by finding a way to clean out chat data by keeping it "client-sided." Meaning all the dialogue is shown on the user's screen, after the data is broadcasted from the server, but is wiped from the database.

I know this idea brings into question of how important it is to preserve such logs for the sake of the chat server. To this, we should definitely discuss the matter.

**Comment by DanWin** [comment]
There are multiple possible options on archiving this:
- Introduce JavaScript, which fetches only new messages. With this, the full log could still be kept on the server and behaviour for clients without JavaScript could remain exactly as before.
- Change the chat script into a long-running process (server) which is always connected and sends data in real-time to the client, either via WebSockets (JavaScript) or a constantly loading page. This will however be incompatible with most (shared) web server providers, since they usually employ a timeout, when a connection is to be closed. If the connection is lost, the JavaScript solution could re-connect and continue adding new messages. Without JavaScript, all history would be lost, potentially resulting in missed messages since you don't always notice when the connection is lost.

**Comment by rexzooly** [comment]
In private messages you could place a handle on each message and when the client gets the message it returns that handle/id and removes it form the DB so not been stored for long on the server, I don't see how this would work on the live chat though without JavaScripting it could be a hard, if it was just normal http/https traffic I would say create a API also where the end dev could make a client what saves the chat in it's own cache, but since this is used a lot on tor as well that option becomes a little harder as the end client would need to connect to tor first.

Without a cache, JS or some way to pool the information though it's not possible, you could add a log window what gets refreshed with the last message so when the next refresh happens to the main chat window there is a local version still hidden in its own window, this isn't a pretty or idea way and it would really work for private messages again.

**Comment by fr33roam3r** [comment]
When I had the idea, I was thinking that the user sends a message to the server, and the server sends it to the clients to be displayed on the page refresh like a queue. I don't know how the refresh waves have been designed, but the server could have a single set time interval to gather and distribute the data universally.

Think of it like this: here are two people in a chat.
`Chat = Welcome!`
`Sender = "Hi!"`

`Chat += Sender`

`Sender = Chat`
`Recipient = Chat`
The chat now says "Welcome! Hi!" for all users.


If all else fails, we could just set a "history limit" to clear data that has been push back by a certain amount of messages.

**Comment by rexzooly** [comment]
The refresh is handled by the client aka the browser and its a default get and post request system, the browser isn't able to store a queue like that, this is why caches and JS bridge them gaps or more advanced tech like web sockets and so on, but the hole point in a system like this is to leave no trace for the of the client on the server and no server on the client, so a client history for one as no place in this framework, YES it can be added without any problems to the code but it would open it up to human error  and snooping as if there is a log sitting somewhere someone can hijack it, it's not a they can't it's just a matter of when they can.

The refresh if you look at the chat are frames and these frames request that basic part of of site again, so if we trying to keep things clean and hidden and removing the information form the server there isn't any place for that information to be stored on the client if browsers could safely do that without JS then it would be epic but the browser it's self without JS is pretty dumb it's just a window nothing more.

Also if you did enable storage on the local client you would also have to protect the 3ed party's using that chat there for encrypt it on the client side and all that BS, but once again JS is a powerful tool and makes it very very unsafe in this kind of system.

Can it be done, yes, should it be done, no as enabling the tools to do it would put it all back at risk.
